# Generated by Django 4.2.11 on 2024-04-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_project', '0002_book_review_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='review',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='berlin_project.book'),
        ),
    ]
