# Generated by Django 4.2.11 on 2024-04-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_project', '0004_alter_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_title',
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='berlin_project.review'),
        ),
    ]
