# Generated by Django 4.2.11 on 2024-04-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_project', '0006_alter_review_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_title',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='berlin_project.book'),
        ),
    ]
